[package]
name = "wrappers"
version = "0.1.8"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg15"]
pg11 = ["pgx/pg11", "pgx-tests/pg11", "supabase-wrappers/pg11" ]
pg12 = ["pgx/pg12", "pgx-tests/pg12", "supabase-wrappers/pg12" ]
pg13 = ["pgx/pg13", "pgx-tests/pg13", "supabase-wrappers/pg13" ]
pg14 = ["pgx/pg14", "pgx-tests/pg14", "supabase-wrappers/pg14" ]
pg15 = ["pgx/pg15", "pgx-tests/pg15", "supabase-wrappers/pg15" ]
pg_test = []

helloworld_fdw = []
db721_fdw = ["serde_json", "serde/derive", "env_logger", "log", "memmap2"]

bigquery_fdw = ["gcp-bigquery-client", "time", "serde_json", "serde", "wiremock", "futures", "yup-oauth2"]
clickhouse_fdw = ["clickhouse-rs", "chrono", "time"]
stripe_fdw = ["reqwest", "reqwest-middleware", "reqwest-retry", "serde_json", "time"]
firebase_fdw = ["reqwest", "reqwest-middleware", "reqwest-retry", "serde_json", "yup-oauth2", "regex", "time"]

# TODO: audit dependencies
airtable_fdw = ["reqwest", "reqwest-middleware", "reqwest-retry", "serde_json", "serde", "url"]

# Does not include helloworld_fdw because of its general uselessness
all_fdws = ["airtable_fdw", "bigquery_fdw", "clickhouse_fdw", "stripe_fdw", "firebase_fdw", "db721_fdw"]

[dependencies]
pgx = { version = "=0.6.1", features = ["time-crate"] }
cfg-if = "1.0"
#supabase-wrappers = "0.1"
supabase-wrappers = { path = "../supabase-wrappers", default-features = false }

# for clickhouse_fdw
clickhouse-rs = { git = "https://github.com/suharev7/clickhouse-rs", branch = "async-await", features = ["tls"], optional = true }
chrono = { version = "0.4", optional = true }

# for bigquery_fdw, firebase_fdw, airtable_fdw and etc.
gcp-bigquery-client = { version = "0.16.5", optional = true }
time = { version = "0.3.17", features = ["parsing"], optional = true }
serde = { version = "1", optional = true }
serde_json = { version = "1.0.86", optional = true }
wiremock = { version = "0.5", optional = true }
futures = { version = "0.3", optional = true }

# for stripe_fdw, firebase_fdw and etc.
reqwest = { version = "0.11.12", features = ["json"], optional = true }
reqwest-middleware = { version = "0.1.6", optional = true }
reqwest-retry = { version = "0.1.5", optional = true }

# for firebase_fdw
yup-oauth2 = { version = "8.0.0", optional = true }
regex = { version = "1", optional = true }

# for airtable_fdw
url = { version = "2.3", optional = true }

env_logger = { version = "*", optional = true }
log = { version = "*", optional = true, features = ["release_max_level_info"] }
memmap2 = { version = "0.5", optional = true }

[dev-dependencies]
pgx-tests = "=0.6.1"

[profile.dev]
panic = "unwind"
lto = "thin"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
